<a href="https://www.kaggle.com/code/olesiadolzhenkova/analysis-the-big-dataset-of-ultra-marathon-running?scriptVersionId=165930192" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# Python project
# I'm still working on this project :) 
# Using this dataset https://www.kaggle.com/datasets/aiaiaidavid/the-big-dataset-of-ultra-marathon-running/data

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import re

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/the-big-dataset-of-ultra-marathon-running/TWO_CENTURIES_OF_UM_RACES
/kaggle/input/the-big-dataset-of-ultra-marathon-running/TWO_CENTURIES_OF_UM_RACES.csv

In [2]:
import seaborn as sns

In [3]:
# Create data frame
df = pd.read_csv("/kaggle/input/the-big-dataset-of-ultra-marathon-running/TWO_CENTURIES_OF_UM_RACES.csv")

/tmp/ipykernel_18/1255982140.py:2: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/kaggle/input/the-big-dataset-of-ultra-marathon-running/TWO_CENTURIES_OF_UM_RACES.csv")

In [4]:
df.head(3)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2

In [5]:
df.tail(3)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
7461192,1995,00.00.1995,Szombathely 24 hours running Race (HUN),24h,3,241.000 km,*Budapest,HUN,1950.0,M,M40,10042.0,1047373
7461193,1995,00.00.1995,Szombathely 24 hours running Race (HUN),24h,3,228.000 km,*Szeged,HUN,1959.0,M,M35,9500.0,380150
7461194,1995,00.00.1995,Szombathely 24 hours running Race (HUN),24h,3,224.000 km,*Pecs,HUN,1958.0,M,M35,9333.0,1070482

In [6]:
df.shape # Rows 7461195

(7461195, 13)

In [7]:
df.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete club                  object
Athlete country               object
Athlete year of birth        float64
Athlete gender                object
Athlete age category          object
Athlete average speed         object
Athlete ID                     int64
dtype: object

In [8]:
# Cleaning the data

In [9]:
# We are only going to use races in the USA which are either 50km or 50Mi and took place in the year 2020.

In [10]:
# Drop rows with missing values
df.dropna(subset=['Event distance/length'], inplace=True)

# Filtering rows where Event distance/length contains '50'
df[df['Event distance/length'].str.contains('50')]['Event distance/length'].unique() # See lot's of dirty data

array(['50km', '50mi', '150km', '250km', '150km/3Etappen', '350mi',
       '500km', '150mi', '250km/6Etappen', '50.6km', '50.5km', '50.7km',
       '50.5mi', '250mi', '250km/5Etappen', '505km', '50.3km',
       '450km/7Etappen', '50.9km', '50.4mi', '50.9mi', '50h',
       '150mi/6Etappen', '550km/6stages', '50.2km', '2500km', '350km',
       '50.4km', '5061km/68stages', '50K', '50.9 mi', '50.8km',
       '1050km/19Etappen', '150km/2Etappen', '450km', '50Km',
       '500km/10Etappen', '50.0km', '50.6mi', '50.74km', '5000km',
       '50.1km', '500mi', '500km/7Etappen', '08:50h', '750km/12stages',
       '503km', '1550km', '16:50h', '50Mile', '50Miles', '50mi+',
       '50miles', '250km/6stages', '503km/7Etappen', '250km/8Etappen',
       '550km', '550km/11Etappen', '5036km/64Etappen', '50km ',
       '250km/7Etappen', '500km/8Etappen', '150mi/4Etappen', '50.69km',
       '1150km/18Etappen', '350km/7Etappen', '150km/4 Etappen', '1500km',
       '504km/7Etappen', '80.450km', '850km/20Etappen',
       '250.7km/6Etappen', '50.7mi', '50.3mi', '350km/6Etappen',
       '550km/9Etappen', '250km/3Etappen', '1500km/20stages', '53.750km',
       '504km', '50.8mi', '150mi/3Etappen'], dtype=object)

In [11]:
# Count the occurrences of each unique value
unique_values = df[df['Event distance/length'].str.contains('50')]['Event distance/length'].unique()

# Create a dictionary to store the counts
counts = {}

# Iterate over the unique values and count occurrences
for value in unique_values:
    count = df[df['Event distance/length'] == value].shape[0]
    counts[value] = count

# Print the counts
for value, count in counts.items():
    print(f"{value}: {count} occurrences")

50km: 1522609 occurrences
50mi: 352181 occurrences
150km: 4401 occurrences
250km: 5950 occurrences
150km/3Etappen: 973 occurrences
350mi: 22 occurrences
500km: 839 occurrences
150mi: 245 occurrences
250km/6Etappen: 9192 occurrences
50.6km: 451 occurrences
50.5km: 1781 occurrences
50.7km: 1030 occurrences
50.5mi: 198 occurrences
250mi: 422 occurrences
250km/5Etappen: 361 occurrences
505km: 1 occurrences
50.3km: 3021 occurrences
450km/7Etappen: 65 occurrences
50.9km: 585 occurrences
50.4mi: 297 occurrences
50.9mi: 165 occurrences
50h: 735 occurrences
150mi/6Etappen: 3 occurrences
550km/6stages: 1 occurrences
50.2km: 675 occurrences
2500km: 3 occurrences
350km: 513 occurrences
50.4km: 2189 occurrences
5061km/68stages: 1 occurrences
50K: 52 occurrences
50.9 mi: 51 occurrences
50.8km: 640 occurrences
1050km/19Etappen: 57 occurrences
150km/2Etappen: 89 occurrences
450km: 145 occurrences
50Km: 124 occurrences
500km/10Etappen: 8 occurrences
50.0km: 204 occurrences
50.6mi: 139 occurrences
50.74km: 164 occurrences
5000km: 4 occurrences
50.1km: 1896 occurrences
500mi: 5 occurrences
500km/7Etappen: 16 occurrences
08:50h: 3 occurrences
750km/12stages: 28 occurrences
503km: 70 occurrences
1550km: 23 occurrences
16:50h: 15 occurrences
50Mile: 32 occurrences
50Miles: 68 occurrences
50mi+: 34 occurrences
50miles: 130 occurrences
250km/6stages: 108 occurrences
503km/7Etappen: 25 occurrences
250km/8Etappen: 27 occurrences
550km: 10 occurrences
550km/11Etappen: 14 occurrences
5036km/64Etappen: 21 occurrences
50km : 263 occurrences
250km/7Etappen: 71 occurrences
500km/8Etappen: 23 occurrences
150mi/4Etappen: 15 occurrences
50.69km: 86 occurrences
1150km/18Etappen: 138 occurrences
350km/7Etappen: 215 occurrences
150km/4 Etappen: 45 occurrences
1500km: 15 occurrences
504km/7Etappen: 1 occurrences
80.450km: 30 occurrences
850km/20Etappen: 11 occurrences
250.7km/6Etappen: 2576 occurrences
50.7mi: 26 occurrences
50.3mi: 13 occurrences
350km/6Etappen: 22 occurrences
550km/9Etappen: 4 occurrences
250km/3Etappen: 24 occurrences
1500km/20stages: 1 occurrences
53.750km: 10 occurrences
504km: 1 occurrences
50.8mi: 61 occurrences
150mi/3Etappen: 8 occurrences

In [12]:
# I see the dity data in Event distance/length column as 50miles, 150km/3Etappen, 50h, 50.9 mi, 50K, 50Km, 250km/6stages, 150km/4 Etappen, 16:50h, 50Mile, 50Miles, 50mi+

In [13]:
# Remove space between values
df['Event distance/length'] = df['Event distance/length'].str.replace(' ', '')
# Check if it works. Last time I saw '50.9 mi'
df[df['Event distance/length'].str.contains('50.9')]['Event distance/length'].unique() # Cool, no space between

array(['50.9km', '50.9mi'], dtype=object)

In [14]:
# Transform xMile, xMiles to xmi
df['Event distance/length'] = df['Event distance/length'].str.replace(r'\b(\d+)\s*Miles?\b', r'\1mi', regex=True)

In [15]:
# Remove everything after / in values like '550km/11Etappen', '5036km/64Etappen', '250km/7Etappen', '850km/20Etappen', '250.7km/6Etappen'
df['Event distance/length'] = df['Event distance/length'].str.split('/').str[0]

In [16]:
df.shape # Rows 7460142
# Keep counting rows to check that my code runs good and I don't lose data unexpectedly

(7460142, 13)

In [17]:
df[df['Event distance/length'].str.contains('50')]['Event distance/length'].unique()

array(['50km', '50mi', '150km', '250km', '350mi', '500km', '150mi',
       '50.6km', '50.5km', '50.7km', '50.5mi', '250mi', '505km', '50.3km',
       '450km', '50.9km', '50.4mi', '50.9mi', '50h', '550km', '50.2km',
       '2500km', '350km', '50.4km', '5061km', '50K', '50.8km', '1050km',
       '50Km', '50.0km', '50.6mi', '50.74km', '5000km', '50.1km', '500mi',
       '08:50h', '750km', '503km', '1550km', '16:50h', '50mi+', '50miles',
       '5036km', '50.69km', '1150km', '1500km', '504km', '80.450km',
       '850km', '250.7km', '50.7mi', '50.3mi', '53.750km', '50.8mi'],
      dtype=object)

In [18]:
# Replace xK,xkmm to xkm
df['Event distance/length'] = df['Event distance/length'].str.replace(r'(\d+)K', r'\1km', regex=True)
df['Event distance/length'] = df['Event distance/length'].str.replace(r'(\d+)kmm', r'\1km', regex=True)

In [19]:
df[df['Event distance/length'].str.contains('50')]['Event distance/length'].unique()

array(['50km', '50mi', '150km', '250km', '350mi', '500km', '150mi',
       '50.6km', '50.5km', '50.7km', '50.5mi', '250mi', '505km', '50.3km',
       '450km', '50.9km', '50.4mi', '50.9mi', '50h', '550km', '50.2km',
       '2500km', '350km', '50.4km', '5061km', '50.8km', '1050km',
       '50.0km', '50.6mi', '50.74km', '5000km', '50.1km', '500mi',
       '08:50h', '750km', '503km', '1550km', '16:50h', '50mi+', '50miles',
       '5036km', '50.69km', '1150km', '1500km', '504km', '80.450km',
       '850km', '250.7km', '50.7mi', '50.3mi', '53.750km', '50.8mi'],
      dtype=object)

In [20]:
# I want to make sure that my code works well and do replacement as I expected. Let's pencil Athlete ID 854481 and row 3275244
df[df['Event distance/length'] == '50mi+']

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
3275244,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,7:13:30 h,Oslo Idrettslag Triath...,NOR,1986.0,M,M35,11.137,854481
3275245,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,8:07:04 h,Nøtterø Rønners,NOR,1984.0,M,M35,9.912,816265
3275246,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,8:59:00 h,Oseberg Bikepark,NOR,1977.0,M,M45,8.957,197842
3275247,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,9:19:47 h,Hell Ultraløperklubb,NOR,1978.0,M,M40,8.625,45733
3275248,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,9:43:29 h,NaN,NOR,1980.0,M,M40,8.274,626455
3275249,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,9:46:13 h,Bamford1869,NOR,1986.0,M,M35,8.236,910399
3275250,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,9:55:51 h,NaN,NOR,1967.0,F,W50,8.103,88201
3275251,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,10:32:54 h,Romerike Ultraløperklubb,NOR,1979.0,F,W40,7.628,115640
3275252,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,10:43:37 h,NaN,NOR,1983.0,M,M35,7.501,874245
3275253,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,11:00:57 h,Team Kikkoman,NOR,1972.0,M,M45,7.305,955224
3275254,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,11:49:56 h,NaN,NOR,1993.0,M,M23,6.801,974794
3275255,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,11:55:32 h,NaN,NOR,1970.0,M,M50,6.747,185386
3275256,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,11:59:15 h,NaN,NOR,1980.0,M,M40,6.713,535409
3275257,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,12:20:38 h,NaN,NOR,1973.0,F,W45,6.519,854544
3275258,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,13:14:53 h,Romerike Ultraløperklubb,GER,1980.0,M,M40,6.074,955934
3275259,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,13:47:39 h,NaN,GBR,1983.0,M,M35,5.833,585452
3275260,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,13:47:40 h,NaN,GBR,1981.0,F,W40,5.833,974795
3275261,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,13:50:34 h,Spirit Friidrettsklubb,NOR,1970.0,M,M50,5.813,482609
3275262,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,14:01:39 h,WAA Ultra / Høyjord IL,NOR,1977.0,F,W40,5.736,145049
3275263,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,14:01:40 h,Rejoggen,NOR,1975.0,M,M45,5.736,842436
3275264,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,14:33:00 h,Romerike Ultraløperklubb,NOR,1965.0,F,W55,5.53,80946
3275265,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,15:23:08 h,NaN,NOR,1975.0,M,M45,5.23,974796
3275266,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,15:23:08 h,NaN,NOR,1976.0,M,M45,5.23,974797
3275267,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,16:09:31 h,NaN,NOR,1990.0,F,W23,4.98,653002
3275268,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,16:09:31 h,NaN,NOR,1988.0,F,W23,4.98,974798
3275269,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,16:14:42 h,Taking Souls,NOR,1989.0,M,M23,4.953,874244
3275270,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,16:17:49 h,Romerike Ultraløperklubb,NOR,1950.0,F,W70,4.938,291019
3275271,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,16:30:47 h,Team Baker Hansen,NOR,1952.0,M,M65,4.873,874250
3275272,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,16:30:47 h,Team Baker Hansen,NOR,1956.0,M,M65,4.873,974799
3275273,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,17:04:32 h,Taking Souls,NOR,2000.0,M,MU23,4.712,974800
3275274,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,17:07:10 h,Taking Souls,NOR,1989.0,M,M23,4.7,974801
3275275,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,17:07:10 h,Taking Souls,NOR,1988.0,M,M23,4.7,974802
3275276,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,17:21:44 h,Taking Souls,NOR,1999.0,F,WU23,4.635,974803
3275277,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,17:27:27 h,NaN,NOR,2000.0,M,MU23,4.609,974804

In [21]:
df[(df['Athlete ID'] == 854481) & (df['Year of event'] == 2022)]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
3275244,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi+,34,7:13:30 h,Oslo Idrettslag Triath...,NOR,1986.0,M,M35,11.137,854481
3599098,2022,22.10.2022,Backyard Sandefjord (NOR),12h,131,80.400 km,OI Triatlon,NOR,1986.0,M,M35,12:00:00,854481

In [22]:
# Replace xmi+ to xmi
df['Event distance/length'] = df['Event distance/length'].str.replace(r'(\d+)mi\+', r'\1mi', regex=True)

In [23]:
# Do the test
df[(df['Athlete ID'] == 854481) & (df['Year of event'] == 2022)]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
3275244,2022,21.-22.05.2022,"Soria Moria til Verdens Ende, 50mi (NOR)",50mi,34,7:13:30 h,Oslo Idrettslag Triath...,NOR,1986.0,M,M35,11.137,854481
3599098,2022,22.10.2022,Backyard Sandefjord (NOR),12h,131,80.400 km,OI Triatlon,NOR,1986.0,M,M35,12:00:00,854481

In [24]:
df[df['Event distance/length'].str.contains('50')]['Event distance/length'].unique()

array(['50km', '50mi', '150km', '250km', '350mi', '500km', '150mi',
       '50.6km', '50.5km', '50.7km', '50.5mi', '250mi', '505km', '50.3km',
       '450km', '50.9km', '50.4mi', '50.9mi', '50h', '550km', '50.2km',
       '2500km', '350km', '50.4km', '5061km', '50.8km', '1050km',
       '50.0km', '50.6mi', '50.74km', '5000km', '50.1km', '500mi',
       '08:50h', '750km', '503km', '1550km', '16:50h', '50miles',
       '5036km', '50.69km', '1150km', '1500km', '504km', '80.450km',
       '850km', '250.7km', '50.7mi', '50.3mi', '53.750km', '50.8mi'],
      dtype=object)

In [25]:
# Transform xmiles to xmi
df['Event distance/length'] = df['Event distance/length'].str.replace(r'\b(\d+)\s*miles?\b', r'\1mi', regex=True)

In [26]:
df[df['Event distance/length'].str.contains('50')]['Event distance/length'].unique()
# I can see hours value in this column but I want focus on data from Russia

array(['50km', '50mi', '150km', '250km', '350mi', '500km', '150mi',
       '50.6km', '50.5km', '50.7km', '50.5mi', '250mi', '505km', '50.3km',
       '450km', '50.9km', '50.4mi', '50.9mi', '50h', '550km', '50.2km',
       '2500km', '350km', '50.4km', '5061km', '50.8km', '1050km',
       '50.0km', '50.6mi', '50.74km', '5000km', '50.1km', '500mi',
       '08:50h', '750km', '503km', '1550km', '16:50h', '5036km',
       '50.69km', '1150km', '1500km', '504km', '80.450km', '850km',
       '250.7km', '50.7mi', '50.3mi', '53.750km', '50.8mi'], dtype=object)

In [27]:
df.isna().sum()

Year of event                      0
Event dates                        0
Event name                         0
Event distance/length              0
Event number of finishers          0
Athlete performance                2
Athlete club                 2826519
Athlete country                    3
Athlete year of birth         588076
Athlete gender                     7
Athlete age category          584853
Athlete average speed            224
Athlete ID                         0
dtype: int64

In [28]:
df[df['Athlete country'].isna()]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
2608252,2020,01.03.2020,Snowies Trail Run Festival (AUS),50km,114,7:52:27 h,Algiers Ninjas,NaN,NaN,F,NaN,6.35,825041
5213425,2011,06.11.2011,50 km-Ultramarathon in Bottrop (GER),50km,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1331804
5216609,2011,30.10.2011,Röntgenlauf (GER),63.3km,383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1331804

In [29]:
# Found all raws where athlete country is Russia. We see 45 983 rows
df[df['Athlete country'] == 'RUS']

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
22,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smole...,6h,9,60.375 km,Мкшч,RUS,1966.0,M,M50,10.063,22
23,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smole...,6h,9,59.750 km,Лично,RUS,1990.0,M,M23,9.958,23
24,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smole...,6h,9,56.250 km,Ахиллес,RUS,1995.0,M,MU23,9.375,24
25,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smole...,6h,9,56.000 km,Аматар,RUS,1956.0,M,M60,9.333,25
26,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smole...,6h,9,55.375 km,Endurance,RUS,NaN,M,NaN,9.229,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7460947,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul (RUS),12h,22,75.650 km,*Barnaul,RUS,NaN,M,NaN,6304.0,1070381
7460948,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul (RUS),12h,22,75.000 km,*Barnaul,RUS,1945.0,M,M45,6250.0,1634258
7460949,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul (RUS),12h,22,70.000 km,*Barnaul,RUS,NaN,M,NaN,5833.0,1641155
7460950,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul (RUS),12h,22,70.000 km,*Barnaul,RUS,1955.0,M,M35,5833.0,249306
7460951,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul (RUS),12h,22,50.000 km,*Barnaul,RUS,NaN,F,NaN,4167.0,1070376

In [30]:
df[df['Event name'].str.contains('(RUS)')]
# 38 598 rows

/tmp/ipykernel_18/385865226.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df['Event name'].str.contains('(RUS)')]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
22,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smole...,6h,9,60.375 km,Мкшч,RUS,1966.0,M,M50,10.063,22
23,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smole...,6h,9,59.750 km,Лично,RUS,1990.0,M,M23,9.958,23
24,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smole...,6h,9,56.250 km,Ахиллес,RUS,1995.0,M,MU23,9.375,24
25,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smole...,6h,9,56.000 km,Аматар,RUS,1956.0,M,M60,9.333,25
26,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smole...,6h,9,55.375 km,Endurance,RUS,NaN,M,NaN,9.229,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7460947,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul (RUS),12h,22,75.650 km,*Barnaul,RUS,NaN,M,NaN,6304.0,1070381
7460948,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul (RUS),12h,22,75.000 km,*Barnaul,RUS,1945.0,M,M45,6250.0,1634258
7460949,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul (RUS),12h,22,70.000 km,*Barnaul,RUS,NaN,M,NaN,5833.0,1641155
7460950,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul (RUS),12h,22,70.000 km,*Barnaul,RUS,1955.0,M,M35,5833.0,249306
7460951,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul (RUS),12h,22,50.000 km,*Barnaul,RUS,NaN,F,NaN,4167.0,1070376

In [31]:
# Create a new df to works with
dfRUS = df[df['Athlete country'] == 'RUS']

In [32]:
dfRUS.shape # Has 45 983 rows

(45983, 13)

In [33]:
dfRUS['Event name'].str.contains('(RUS)')

/tmp/ipykernel_18/3713047054.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  dfRUS['Event name'].str.contains('(RUS)')

22         True
23         True
24         True
25         True
26         True
           ...
7460947    True
7460948    True
7460949    True
7460950    True
7460951    True
Name: Event name, Length: 45983, dtype: bool

In [34]:
dfRUS['Event name'] = dfRUS['Event name'].str.replace('(RUS)', '').str.strip()

/tmp/ipykernel_18/3920062043.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfRUS['Event name'] = dfRUS['Event name'].str.replace('(RUS)', '').str.strip()

In [35]:
dfRUS['Event name'].str.contains('(RUS)')

/tmp/ipykernel_18/3713047054.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  dfRUS['Event name'].str.contains('(RUS)')

22         False
23         False
24         False
25         False
26         False
           ...
7460947    False
7460948    False
7460949    False
7460950    False
7460951    False
Name: Event name, Length: 45983, dtype: bool

In [36]:
dfRUS.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete club                  object
Athlete country               object
Athlete year of birth        float64
Athlete gender                object
Athlete age category          object
Athlete average speed         object
Athlete ID                     int64
dtype: object

In [37]:
dfRUS['Athlete year of birth'] 
# See the floating value. I wan't to convert them into int but before I need to make sure that only 0 after dot

22         1966.0
23         1990.0
24         1995.0
25         1956.0
26            NaN
            ...
7460947       NaN
7460948    1945.0
7460949       NaN
7460950    1955.0
7460951       NaN
Name: Athlete year of birth, Length: 45983, dtype: float64

In [38]:
# Check if any value in the 'Athlete year of birth' column has a non-zero digit after the decimal point
dfRUS['Athlete year of birth'].unique()

array([1966., 1990., 1995., 1956.,   nan, 1986., 1972., 1971., 1958.,
       1957., 1949., 1944., 1969., 1979., 1945., 1950., 1974., 1961.,
       1960., 1973., 1985., 1970., 1959., 1997., 1999., 1978., 1982.,
       1983., 1965., 1984., 1976., 1989., 1988., 1977., 1963., 1964.,
       1981., 1954., 1962., 1975., 1991., 1987., 1967., 2004., 1951.,
       1992., 1994., 1993., 1968., 1935., 1980., 1955., 1952., 1934.,
       1998., 1996., 1953., 1947., 1941., 2000., 1946., 1939., 2001.,
       1937., 1942., 1940., 1948., 2011., 2002., 2003., 2005., 1938.,
       1943., 1931., 1936., 1930., 1932., 1926., 1929., 1921., 1933.,
       1928., 1924., 1927., 1923.])

In [39]:
dfRUS['Athlete year of birth'] = dfRUS['Athlete year of birth'].fillna(0).astype(int)
# I can't do this, I need to change ot for whole dataset

/tmp/ipykernel_18/431633012.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfRUS['Athlete year of birth'] = dfRUS['Athlete year of birth'].fillna(0).astype(int)

In [40]:
# Check that in whole dataset only 0 after dot
df['Athlete year of birth'].unique()

array([1978., 1981., 1987., 1976., 1992., 1974., 1979., 1967., 1985.,
       1977.,   nan, 1990., 1971., 1956., 1966., 1995., 1986., 1972.,
       1980., 1982., 1989., 1975., 1961., 1964., 1963., 1973., 1983.,
       1988., 1991., 1965., 1970., 1984., 1996., 1968., 1960., 1969.,
       1962., 1999., 2006., 1998., 1958., 1957., 1949., 1944., 1945.,
       1994., 1950., 1951., 1953., 1959., 1952., 1954., 1955., 1943.,
       1993., 1997., 2000., 2002., 2001., 1947., 1948., 1942., 1946.,
       1941., 1938., 1937., 1939., 2004., 2007., 2003., 1940., 2005.,
       1936., 2010., 1935., 2008., 2011., 1934., 2016., 1924., 2009.,
       1923., 1932., 1933., 1922., 2017., 2012., 1931., 1929., 1904.,
       1927., 1930., 1917., 2014., 2013., 2018., 1920., 1928., 1919.,
       2019., 1901., 1193., 1926., 2021., 2020., 1910., 1921., 1925.,
       1911., 1916., 1918., 1900., 1908., 1878., 1914., 1913., 1915.,
       1905., 1786., 1791., 1839., 1831., 1846., 1840., 1841., 1845.,
       1847., 1853., 1856., 1852., 1849., 1844., 1824., 1832., 1843.,
       1842., 1851., 1854., 1833., 1848., 1850., 1838., 1857., 1862.,
       1858., 1835., 1836., 1837., 1861., 1859., 1867., 1855., 1863.,
       1871., 1868., 1873., 1870., 1816., 1869., 1864., 1872., 1874.,
       1875., 1834., 1865., 1866., 1860., 1876., 1877., 1817., 1882.,
       1883., 1887., 1885., 1888., 1893., 1890., 1895., 1906., 1891.,
       1889., 1884., 1902., 1892., 1903., 1896., 1898., 1907., 1894.,
       1886., 1912., 1909., 1897., 1899.])

In [41]:
# Change the column into int and replace NaN with 0
df['Athlete year of birth'].fillna(0).astype(int)

0          1978
1          1981
2          1987
3          1976
4          1992
           ...
7461190       0
7461191       0
7461192    1950
7461193    1959
7461194    1958
Name: Athlete year of birth, Length: 7460142, dtype: int64

In [42]:
# Make sure that code works
df.dtypes
# Athlete year of birth is int64 now

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete club                  object
Athlete country               object
Athlete year of birth        float64
Athlete gender                object
Athlete age category          object
Athlete average speed         object
Athlete ID                     int64
dtype: object

In [43]:
# Let's assess the number of missing values in the "Athlete year of birth" column
dfRUS[dfRUS['Athlete year of birth'] == 0]
# We have 1 334 rows with missing date of birth

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
26,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smolensk,6h,9,55.375 km,Endurance,RUS,0,M,NaN,9.229,26
29,2018,06.01.2018,6 Stunden Self-Transcendence Sri Chinmoy Smolensk,6h,9,50.500 km,Лично,RUS,0,M,NaN,8.417,29
42986,2018,24.-25.02.2018,Transgrancanaria advanced 64 km (ESP),64km,744,8:55:33 h,4E Sutki,RUS,0,M,NaN,7.17,40039
53934,2018,11.02.2018,Winter Marathon Titan,50km,34,4:25:41 h,NaN,RUS,0,M,NaN,11.292,49205
53935,2018,11.02.2018,Winter Marathon Titan,50km,34,4:26:48 h,NaN,RUS,0,M,NaN,11.244,1827
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7460945,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul,12h,22,82.320 km,*Novokuzneck,RUS,0,M,NaN,6860.0,1641153
7460946,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul,12h,22,80.000 km,*Novosibirsk,RUS,0,M,NaN,6667.0,1641154
7460947,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul,12h,22,75.650 km,*Barnaul,RUS,0,M,NaN,6304.0,1070381
7460949,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul,12h,22,70.000 km,*Barnaul,RUS,0,M,NaN,5833.0,1641155
7460951,1995,28.01.1995,Open AGTU 12 hours race trophy Barnaul,12h,22,50.000 km,*Barnaul,RUS,0,F,NaN,4167.0,1070376

In [44]:
# Check maybe I can fix some missing values
dfRUS[(dfRUS['Athlete year of birth'] == 0) & dfRUS['Athlete age category'].notna()]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
915935,2016,28.05.2016,Desert Steppes Marathon / Elton Ultra-Trail - ...,56km,52,6:16:37 h,NaN,RUS,0,M,M23,8.922,5265
994105,2016,24.07.2016,Golden Ring 50 Km Ultra Trail,50km,380,5:48:22 h,NaN,RUS,0,M,M23,8.612,5265
1054593,2016,05.-08.10.2016,Crimea X Run - Stage Race (UKR),155km,112,24:00:30 h,NaN,RUS,0,M,M23,6.456,5265
1440426,2017,23.04.2017,X-Race Wild Trail,50km,29,7:15:44 h,NaN,RUS,0,M,M23,6.885,5265
1669047,2017,12.-15.10.2017,Crimea X Run - Stage Race (UKR),158km,203,28:04:46 h,NaN,RUS,0,M,M23,5.627,5265
2008359,2019,25.05.2019,Elton Volgabus Ultra-Trail – Elton Night Ultra,84km,149,8:10:40 h,NaN,RUS,0,M,M23,10.272,5265

In [45]:
# I need to create new column with age based on Athlete age category

In [46]:
df['Athlete age category'].unique()

array(['M35', 'M23', 'M40', 'W35', 'W50', nan, 'W23', 'M50', 'M45', 'M60',
       'MU23', 'W45', 'M55', 'W40', 'WU23', 'M65', 'W70', 'M70', 'W55',
       'W60', 'M30', 'W30', 'W65', 'M75', 'M20', 'WU20', 'W20', 'M80',
       'W75', 'MU20', 'W80', 'M90', 'M85', 'M95', 'W85', 'W95', 'F35',
       'W90'], dtype=object)

In [47]:
df['Athlete age category'] = df['Athlete age category'].fillna(0)

In [48]:
# Test that NaN was replaced by 0
df[df['Athlete age category'].isna()]

Empty DataFrame
Columns: [Year of event, Event dates, Event name, Event distance/length, Event number of finishers, Athlete performance, Athlete club, Athlete country, Athlete year of birth, Athlete gender, Athlete age category, Athlete average speed, Athlete ID]
Index: []

In [49]:
# Extract numeric part from 'Athlete age category' column
# df['Age_Category_Numeric'] = df['Athlete age category'].str.extract('(\d+)').astype(float).astype(pd.Int64Dtype())

# Replace 0 values in 'Athlete year of birth' column with the calculation
# df['Athlete year of birth'] = df['Athlete year of birth'].mask(df['Athlete year of birth'] == 0, df['Year of event'] - df['Age_Category_Numeric'])

# df.drop(columns=['Age_Category_Numeric'], inplace=True)

In [50]:
# dfRUS[(dfRUS['Athlete ID'] == 5265)]
# Looks like it wasn't good idea to fix missing values with age category as in 2016,2017 and 2018 the athlet 5265 has the same age category
# I googled and under M23/W23 category age from 23-34 years old. I can't calculate the age based on age category. I have to remove missing values

In [51]:
# Before I drop 0 (NaN in past) values from 'Athlete year of birth' in dfRUS, I'd like to calculate %
percentage_zeros = (dfRUS['Athlete year of birth'] == 0).mean() * 100

print(f"The percentage of zero values in 'Athlete year of birth' column: {percentage_zeros:.2f}%")

The percentage of zero values in 'Athlete year of birth' column: 2.90%

In [52]:
# Filter out 0 values as they're less that 5% from all data
dfRUS = dfRUS[dfRUS['Athlete year of birth'] != 0]

In [53]:
# Check that the previous code works
dfRUS[dfRUS['Athlete year of birth'] == 0]

Empty DataFrame
Columns: [Year of event, Event dates, Event name, Event distance/length, Event number of finishers, Athlete performance, Athlete club, Athlete country, Athlete year of birth, Athlete gender, Athlete age category, Athlete average speed, Athlete ID]
Index: []